---
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  api:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://user:password@db/example
